# Site
darkmode: false
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Jason Leung
title: PhD Student at Columbia University
email: jason[dot]leung[at]columbia.edu
website: http://jasonhleung.com

# Social links
twitter_username: nosajason101
github_username:  ceanothus
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
linkedin_username: jason-leung-a57ba0132
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hey there! I'm an aspiring evolutionary biologist and botanist. 
  
  My mission is to study and protect our natural heritage in the field, lab, and command line. 
  I want to push a frontier in our science by learning and applying modern genomic tools.
  
  Right now, I'm a PhD student the Department of Ecology, Evolution, and Environmental Biology at Columbia University, where I am under the mentorship of Deren Eaton. My work focuses on mating systems evolution in *Amaranthus*.
  I am particularly interested in the genomic mechanisms and ecological consequences of transitions to and from dioecy, as well the recent phylogeography of the threatened coastal plant species, *A. pumilus*.
  
  
  <mark>UPDATES:</mark>

  **2025.01.30**: Updated this website for my class!
  
  **2023.04.21**: Check out our [genome announcement](https://doi.org/10.1094/PHYTOFR-03-23-0027-A) in PhytoFrontiers for *Marasmius tenuissimus*, an emerging fungal pathogen of cacao 
  
  **2023.04.12**: After receiving offers from 3 graduate schools, I've decided to attend Columbia University in the fall! 
  Many thanks to all my friends and family, my recommenders, and the advisors that welcomed me to their labs for visits. 
  
  **2020.04.04**: I set up this website! Based on a Jekyll design by sproogen.

# Education Section
educaton_title: Education

# Experience Section
experience_title: Experience

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
 

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
 
