# Site
darkmode: false
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Jason Leung
title: Student at UCLA
email: leung.jasonh@gmail.com
website: http://jasonhleung.com

# Social links
twitter_username: nosajason101
github_username:  ceanothus
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
linkedin_username: jason-leung-a57ba0132
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hey there! My name's Jason and I'm a student at the University of California, Los Angeles. Right now I'm working towards a B.S in Ecology, Behavior, and Evolution with a minor in Bioinformatics.
  
  I'm also a GreenLabs Fellow at the school's Office of Environment, Health, and Safety (EH&S) where I cooperate with scientists, staff, and students to reduce the environmental impact of laboratory research.

  My mission is to study and protect our natural heritage in the field, lab, and command line. I want to push a frontier in evolutionary biology by learning and applying modern computational skills.

  <bold>Updates</bold>
  
  <mark>2020.04.04:</mark> I set up this website! Based on a Jekyll design by sproogen.
# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Rock climbing
   - Gaming
   - Knitting
   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
 
